// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hockey-dashboard/ExpandedViews.tsx": () => import("../components/mockups/hockey-dashboard/ExpandedViews.tsx"),
  "./components/mockups/hockey-dashboard/InteractiveDashboard.tsx": () => import("../components/mockups/hockey-dashboard/InteractiveDashboard.tsx"),
  "./components/mockups/hockey-dashboard/LoginScreen.tsx": () => import("../components/mockups/hockey-dashboard/LoginScreen.tsx"),
  "./components/mockups/hockey-dashboard/OnboardingModal.tsx": () => import("../components/mockups/hockey-dashboard/OnboardingModal.tsx"),
  "./components/mockups/hockey-dashboard/shared.tsx": () => import("../components/mockups/hockey-dashboard/shared.tsx"),
  "./components/mockups/hockey-dashboard/pages/CalendarPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/CalendarPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/FeaturedInsightsPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/FeaturedInsightsPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/NotesPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/NotesPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/PlayerInsightsPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/PlayerInsightsPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/PreferencesPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/PreferencesPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/StatsPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/StatsPage.tsx"),
  "./components/mockups/hockey-dashboard/pages/VideoPage.tsx": () => import("../components/mockups/hockey-dashboard/pages/VideoPage.tsx"),
  "./components/mockups/hockey-dashboard/widgets/NewWidgets.tsx": () => import("../components/mockups/hockey-dashboard/widgets/NewWidgets.tsx")
};
